religious_activity: list[str] = [
    "offering",
    "tithe",
    "Covenant seed",
    "prayer",
    "worship",
    "fasting",
    "pilgrimage",
    "baptism",
    "communion",
    "tithing",
    "offering",
    "charity",
    "evangelism",
    "preaching",
    "sermon",
    "fellowship",
    "meditation",
    "bible study",
    "quran recitation",
    "chanting",
    "confession",
    "confirmation",
    "bar mitzvah",
    "hajj",
    "umrah",
    "sacrifice",
    "ordination",
    "rosary",
    "mass",
    "sabbath",
    "wedding blessing",
    "naming ceremony",
    "funeral rites",
    "holy communion",
    "almsgiving",
    "spiritual retreat",
    "anointing",
    "thanksgiving service",
    "religious counseling",
    "gospel crusade",
    "missionary work",
    "holy convocation",
    "revival service",
    "prophetic service",
    "redeemed christian church of God",
    "rccg",
    "living faith church",
    "winners chapel",
    "dunamis international gospel centre",
    "mountain of fire",
    "mfm",
    "christ embassy",
    "loveworld",
    "deeper life bible church",
    "catholic church",
    "anglican church",
    "daystar christian centre",
    "commonwealth of zion assembly",
    "coza",
    "house on the rock",
    "four square gospel church",
    "dominion city",
    "scoan",
    "synagogue church of all nations",
    "celestial church",
    "ccc",
    "christ apostolic church",
    "cac",
    "ecwa",
    "assemblies of God",
    "methodist church",
    "new covenant church",
    "salvation ministries",
    "household of God church",
    "jubilee christian church",
    "harvesters international",
    "global impact church",
    "christ lifeline ministry",
    "latter rain assembly",
    "the elevation church",
    "central mosque",
    "national mosque",
    "lagos central mosque",
    "abuja national mosque",
    "church",
    "mosque",
    "offering",
    "tithe",
    "thanksgiving",
    "sadaqah",
    "zakat",
    "ramadan",
    "eid",
    "fasting",
    "prayer",
    "service",
    "imam",
    "pastor",
    "cathedral",
    "worship",
    "alms",
    "hajj",
    "pilgrimage",
    "islamic center",
    "christian centre",
    "revival",
    "ministry",
    "chapel",
    "clergy",
    "sermon",
    "devotion",
    "donation",
    "church building fund",
    "church contribution",
    "mosque fund",
]


fees: list[str] = ["vat", "levy", "charge", "visa"]

gambling_or_betting: list[str] = [
    "sporty",
    "CHOPBARH",
    "Bet9ja",
    "Betway Nigeria",
    "Betano",
    "1xBet",
    "BetKing",
    "SportyBet",
    "NairaBet",
    "MerryBet",
    "BetBaba",
    "22Bet",
    "Betwinner",
    "Bangbet",
    "Mozzartbet",
    "Melbet",
    "Easywin Lotto",
    "Bet9ja",
    "Betway Nigeria",
    "BetKing",
    "22Bet",
    "Betwinner",
    "Betfair",
    "Melbet",
    "1XBet",
    "NairaBet",
    "SportyBet",
    "Paripesa",
    "BetPawa",
    "Afropari",
    "Sportaza",
    "Betobet",
    "LiveScoreBet",
    "BC Game Sports Betting",
    "Msport",
]

cabletv_streaming: list[str] = [
    "DSTV",
    "GOtv",
    "Netflix",
    "Amazon Prime Video",
    "Hulu",
    "Disney+",
    "HBO Max",
    "YouTube",
    "Apple TV+",
    "Peacock",
    "Paramount+",
    "Tubi",
    "Vudu",
    "FuboTV",
    "Crackle",
    "Rakuten TV",
    "Mubi",
    "Shudder",
    "Sling TV",
    "iROKOtv",
    "Showmax",
    "OnDemand Africa",
    "Kwese Play",
    "Afrinolly",
    "TVC Play",
    "Nollywood TV",
    "Viewza",
    "Pulse TV",
]
loan_repayment = [
    "Interest",
    "FairMoney",
    "Carbon",
    "Branch",
    "Palmcredit",
    "QuickCheck",
    "Aella Credit",
    "KiaKia",
    "Migo",
    "Lidya",
    "FINT",
    "Kwaba",
    "Lendha",
    "Owoafara",
    "Soko Loan",
    "Xcrosscash",
    "EaseMoni",
    "CashLion",
    "GoCash",
    "RenMoney",
    "Zedvance",
    "C24",
    "Okash",
    "Credit Direct",
    "Specta",
    "Pay Later",
]


savings_and_investments: list[str] = [
    "credit life insurance",
    "overwood",
    "arm money market",
    "uba nominee first",
    "volition",
    "piggyvest",
    "cowryw",
    "cowrywise",
    "bamboo sys",
    "sumotrust",
    "afrinvest",
    "wealthng",
    "chaka tech",
    "trove tech",
    "mutual fund",
    "fsdh",
    "axa mansard",
    "thrive agric",
    "farmfunded",
    "agrilet",
    "crowdyvest",
    "agrorite",
    "farmsponsor",
    "farm360",
    "westagro",
    "farmcrowdy",
    "risevest",
    "kolopay",
    "smart save",
    "meristem",
    "vetiva",
    "cordros",
    "pettysave",
    "cititrust",
    "arm securities",
    "aiico",
    "de lords securities",
    "core securities",
    "kinley securities",
    "apt securities",
    "cardinalstone",
    "norrenberger",
    "passfolio",
    "prominent securities",
    "first trustees",
    "fbnquest",
    "fbn money market",
    "fbn capital asset",
    "union trustees",
    "fixed dep",
    "credit assist invest",
    "capital one investment",
    "anchoria invest",
    "zara capital",
    "creditcrest",
    "uba money market",
    "ibtc money market",
    "ibtc asset",
    "coronation money market",
    "csl stockbrokers",
    "legacy money market",
    "abacus money market",
    "edc nigeria money market",
    "money market fund",
    "icon stockbrokers",
    "trw stockbrokers",
    "horizon stockbrokers",
    "fsl asset",
    "cowry asset",
    "united capital asset",
    "trustbanc asset",
    "core asset",
    "first ally asset",
    "nobleserve capital",
    "alpha morgan capital",
    "leo targeted saving",
    "leo recurrent saving",
    "monthly saving",
    "target saving",
    "fgsatsa goal top up",
    "festivesave",
    "paymyrent nigeria",
    "digikolo",
    "wealthbuddy",
    "investnow",
    "payday invest",
    "fandk savings",
    "i-invest",
    "parthian partner",
    "yoocharr",
    "investa ng",
    "stashbox",
    "ziing",
    "money market",
    "goal created",
    "goal topup",
    "stash created",
    "coop savings",
    "savings successful",
    "xmas savings",
    "octafx",
    "mkt fund",
    "market fund",
    "mutual benefit",
    "equity fund",
    "axa mmf",
    "arm mmf",
    "axa-mmf",
    "monthly contr",
    "esusu",
    "monthlysav",
    "monthly sav",
    "weekly sav",
    "weeklysav",
    "monthly ajo",
    "weekly ajo",
    "ajo contr",
    "flexible sav",
    "savings from expenses",
    "spend and save",
    "axamansard",
    "autosave",
    "spend & save",
    "owealth",
    "owealth investment",
    "flexible save",
    "flexible savings",
    "stockbrokers",
]

pensions = [
    "Stanbic IBTC Pension Managers",
    "PenCom (National Pension Commission)",
    "Leadway Pensure Pension Fund Custodian",
    "Trustfund Pension Plc",
    "Investment One Pension Managers",
    "AIICO Pension Managers",
    "Fidelity Pension Managers",
    "Access Pension Fund Custodian",
    "UBA Pension Custodian",
    "Veritas Glanvills Pensions",
    "Nova Pensions",
    "Crusader Sterling Pensions",
    "Zenith Pensions",
    "Mutual Benefits Pensions",
    "Pensions Alliance Limited (PAL Pensions)",
    "First Guarantee Pension Ltd",
    "Premium Pension Limited",
    "Guaranty Trust Pension",
    "Sigma Pensions",
    "Access ARM Pensions Limited",
    "Cardinal Stone Pensions Limited",
    "Citizens Pensions Limited",
    "Crusader Sterling Pensions Limited",
    "FCMB Pensions Limited",
    "Fidelity Pension Managers Limited",
    "Guaranty Trust Pension Managers Limited",
    "Leadway Pensure PFA Limited",
    "NUPMCO Pensions Limited",
    "NLPC PFA Limited",
    "Norrenberger Pensions Limited",
    "NPF Pensions Limited",
    "Oak Pensions Limited",
    "PAL Pensions Limited",
    "Premium Pension Limited",
    "Stanbic IBTC Pension Managers Limited",
    "Tangerine APT Pensions Limited",
    "Trustfund Pensions Limited",
    "Vesta Pension Limited",
    "retirement",
    "retiree",
]

health: list[str] = [
    "tuberculosis",
    "yellow fever",
    "covid",
    "general hospital",
    "teaching hospital",
    "medical center",
    "health center",
    "specialist hospital",
    "emergency room",
    "clinic",
    "maternity",
    "diagnostics center",
    "children's hospital",
    "pharmacy",
    "chemist",
    "drugstore",
    "meds",
    "prescription",
    "over-the-counter",
    "medication",
    "otc",
    "supplement",
    "vitamins",
    "pills",
    "capsules",
    "pain relief",
    "antibiotics",
    "injections",
    "lab test",
    "diagnostics",
    "x-ray",
    "scan",
    "mri",
    "bloodwork",
    "ct scan",
    "ultrasound",
    "medical test",
    "covid test",
    "pcr",
    "hmo checkup",
    "wellness check",
    "HMO",
    "health insurance",
    "NHIS",
    "healthcare plan",
    "insurance premium",
    "medicare",
    "medicaid",
]

internet_and_telecom: list[str] = ["airtime", "data", "internet"]

person: list[str] = [
    "Abimbola",
    "Adaku",
    "Adaobi",
    "Ayomide",
    "Chibuzor",
    "Chidiogo",
    "Chinonso",
    "Chukwubuikem",
    "Ebelechukwu",
    "Ifeanyichukwu",
    "Ikenna",
    "Ngozi",
    "Olamide",
    "Olufunke",
    "Oluwafemi",
    "Oluwaseun",
    "Oluwatobi",
    "Somtochukwu",
    "Temitope",
    "Mohammed",
]

banking_organizations: list[str] = [
    "access bank",
    "first bank",
    "fbn",
    "gtbank",
    "gt bank",
    "union bank",
    "sterling",
    "alat by wema bank",
    "alat",
    "fidelity bank",
    "opay",
    "uba",
    "zenith bank",
    "kuda",
    "fcmb",
    "moniepoint",
    "stanbic ibtc bank plc",
    "accion microfinance bank",
    "heritage bank",
    "palmpay",
    "standard chartered",
    "providus bank",
    "polaris bank limited",
    "ecobank",
    "unity bank",
    "keystone bank",
    "united bank for africa (uba)",
    "titan bank",
]

location: list[str] = [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Ibadan",
    "Kano",
    "Enugu",
    "Benin City",
    "Kaduna",
    "Aba",
    "Jos",
    "Lekki",
    "Ikoyi",
    "Ikeja",
    "Lagos Island",
    "Isolo",
    "Oniru Private Beach",
    "Gym",
]

organization: list[str] = [
    "Justrite",
    "paystack",
    "Flutterwave",
    "Interswitch",
    "Google LLC",
    "FoodCo stores",
    "Shoprite",
    "Rejoice Supermarket",
    "ABC Transport Ltd",
    "Indicina Enterprises",
    "Coca Cola Inc",
    "Microsoft Corp",
    "GlaxoSmithKline PLC",
    "Olgin Stores",
    "Burberry Group",
    "Cubana Holding Company",
    "Orient International",
    "ABC Consulting Services",
    "Accenture Security Solutions",
    "Indicina Technologies",
    "Alpha Partners",
    "Core Ventures",
]

__all__: list[str] = [
    "religious_activity",
    "fees",
    "gambling_or_betting",
    "cabletv_streaming",
    "loan_repayment",
    "savings_and_investments",
    "pensions",
    "health",
    "internet_and_telecom",
    "banking_organizations",
    "person",
    "location",
    "organization",
]
